# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Part 1 - Data Preprocessing

In [3]:
!pip install odfpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 717.0/717.0 kB 4.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for odfpy: filename=odfpy-1.4.1-py2.py3-none-any.whl size=160673 sha256=dc1fc41d1b0c0f10197c38b37d1c97679952eee14a774e0e93ad9be958c2c017
  Stored in directory: /root/.cache/pip/wheels/c8/2e/95/90d94fe33903786937f3b8c33dd88807f792359c6424b40469
Successfully built odfpy


### Importing the dataset

Features consist of hourly average ambient variables
- Temperature (T) in the range 1.81°C and 37.11°C,
- Ambient Pressure (AP) in the range 992.89-1033.30 milibar,
- Relative Humidity (RH) in the range 25.56% to 100.16%
- Exhaust Vacuum (V) in teh range 25.36-81.56 cm Hg
- Net hourly electrical energy output (EP) 420.26-495.76 MW
The averages are taken from various sensors located around the plant that record the ambient variables every second. The variables are given without normalization.


In [8]:
dataset = pd.read_excel('Folds5x2_pp.ods',engine='odf')
print(dataset.info)
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

<bound method DataFrame.info of          AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]>


In [5]:
X

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [6]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

### Splitting the dataset into the Training set and Test set

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

**Feature Scaling**

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [20]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [21]:
# dense creates fully connected 'dense' layers
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [22]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [23]:
# regression => activation function = None
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [24]:
ann.compile(optimizer='adam', loss='mean_squared_error')

### Training the ANN model on the Training set

In [25]:
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 2ms/step - loss: 205277.7031
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 198522.0625
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 178481.3906
Epoch 4/100
240/240 [==============================] - 1s 2ms/step - loss: 141530.6250
Epoch 5/100
240/240 [==============================] - 0s 2ms/step - loss: 93657.1406
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 53187.9609
Epoch 7/100
240/240 [==============================] - 0s 2ms/step - loss: 31614.8652
Epoch 8/100
240/240 [==============================] - 1s 2ms/step - loss: 23668.4141
Epoch 9/100
240/240 [==============================] - 1s 2ms/step - loss: 20039.8496
Epoch 10/100
240/240 [==============================] - 1s 2ms/step - loss: 17089.5137
Epoch 11/100
240/240 [==============================] - 1s 2ms/step - loss: 14178.0537
Epoch 12/100
240/240 [==========================

### Predicting the results of the Test set

In [26]:
y_pred = ann.predict(x_test)
print(np.concatenate((y_test.reshape(-1, 1),y_pred.reshape(-1, 1)),axis = 1))

60/60 [==============================] - 0s 2ms/step
[[431.23       432.08657837]
 [460.01       459.05892944]
 [461.14       463.08145142]
 ...
 [473.26       469.92636108]
 [438.         441.78805542]
 [463.28       461.17028809]]
